### ISSUE TITLE
Application crashes when we add contact with phone longer then 10 digits

### ISSUE THREAD

**Issue by JuliestJu** [RSMNYS/iBook#58]
![Image](https://github.com/RSMNYS/iBook/assets/46191250/bbf1bf9f-4b8d-492c-b86d-5a5fd11f423e)

**Comment by JuliestJu** [comment]
Traceback (most recent call last):
  File "/Users/julia/Developer/PythonProjects/FinProj/main.py", line 50, in <module>
    main()
  File "/Users/julia/Developer/PythonProjects/FinProj/main.py", line 40, in main
    dispatcher.dispatch(command, *args, address_book=book, notes=notes)
  File "/Users/julia/Developer/PythonProjects/FinProj/src/commands/command_dispatcher.py", line 44, in dispatch
    command.execute(*args, **kwargs)
  File "/Users/julia/Developer/PythonProjects/FinProj/src/address_book/address_book_commands.py", line 20, in execute
    self._add_new_contact(address_book)
  File "/Users/julia/Developer/PythonProjects/FinProj/src/address_book/address_book_commands.py", line 27, in _add_new_contact
    record.add_phone(PhonePrompt().field)
  File "/Users/julia/Developer/PythonProjects/FinProj/src/address_book/record.py", line 15, in add_phone
    raise ValueError(f"Phone number: {phone} is wrong")
ValueError: Phone number: 12345678901 is wrong
