### ISSUE TITLE
Application crashes when we edit contacts phone number with number > 10 digits

### ISSUE THREAD

**Issue by JuliestJu** [RSMNYS/iBook#59]
![Image](https://github.com/RSMNYS/iBook/assets/46191250/3c0cc539-2c6e-4c03-9b4a-5334c40e0f77)

**Comment by JuliestJu** [comment]
Traceback (most recent call last):
  File "/Users/julia/Developer/PythonProjects/FinProj/main.py", line 50, in <module>
    main()
  File "/Users/julia/Developer/PythonProjects/FinProj/main.py", line 40, in main
    dispatcher.dispatch(command, *args, address_book=book, notes=notes)
  File "/Users/julia/Developer/PythonProjects/FinProj/src/commands/command_dispatcher.py", line 44, in dispatch
    command.execute(*args, **kwargs)
  File "/Users/julia/Developer/PythonProjects/FinProj/src/address_book/address_book_commands.py", line 150, in execute
    self._edit_contact(address_book)
  File "/Users/julia/Developer/PythonProjects/FinProj/src/address_book/address_book_commands.py", line 178, in _edit_contact
    record.add_phone(phone)
  File "/Users/julia/Developer/PythonProjects/FinProj/src/address_book/record.py", line 15, in add_phone
    raise ValueError(f"Phone number: {phone} is wrong")
ValueError: Phone number: 12345678901 is wrong
