### ISSUE TITLE
Application crashes when user searches by email

### ISSUE THREAD

**Issue by JuliestJu** [RSMNYS/iBook#60]
![Image](https://github.com/RSMNYS/iBook/assets/46191250/9eef8e96-820f-4344-9716-6891f5787084)

**Comment by JuliestJu** [comment]
Traceback (most recent call last):
  File "/Users/julia/Developer/PythonProjects/FinProj/main.py", line 50, in <module>
    main()
  File "/Users/julia/Developer/PythonProjects/FinProj/main.py", line 40, in main
    dispatcher.dispatch(command, *args, address_book=book, notes=notes)
  File "/Users/julia/Developer/PythonProjects/FinProj/src/commands/command_dispatcher.py", line 44, in dispatch
    command.execute(*args, **kwargs)
  File "/Users/julia/Developer/PythonProjects/FinProj/src/address_book/address_book_commands.py", line 192, in execute
    self._search_contact(search_parameter, query, address_book)
  File "/Users/julia/Developer/PythonProjects/FinProj/src/address_book/address_book_commands.py", line 195, in _search_contact
    result = address_book.search(search_parameter, query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/julia/Developer/PythonProjects/FinProj/src/address_book/address_book.py", line 73, in search
    return searcher.search_contact(self, parameter, query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/julia/Developer/PythonProjects/FinProj/src/address_book/address_book_searcher.py", line 23, in search_contact
    return self.search_by_email(address_book, query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/julia/Developer/PythonProjects/FinProj/src/address_book/address_book_searcher.py", line 57, in search_by_email
    if query.lower() in record.email.value.lower():
                        ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
